### PR TITLE
APP-34433: Small bug fix and bit cleaner example

### PR DESCRIPTION
**Pull request by tonsV2**
Automatically created JIRA issue: [APP-34433](https://habxfr.atlassian.net/browse/APP-34433)

[APP-34433]: https://habxfr.atlassian.net/browse/APP-34433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by clementlecorre — APPROVED** [review]

**Comment by clementlecorre** [comment]
@tonsV2 Can you update package.json with
```
-  "version": "0.7.0"
+  "version": "0.6.0"
```
For using patch method

**Comment by tonsV2** [comment]
> @tonsV2 Can you update package.json with
> 
> ```
> -  "version": "0.7.0"
> +  "version": "0.6.0"
> ```
> 
> For using patch method

Done! Please test before merging :pray:

**Comment by clementlecorre** [comment]
Ouups,  Sorry it's `0.6.1`

**Comment by clementlecorre** [comment]
Yes I have tested your change :)

We remove the excess endl on the streams.

before
```
pg_dump: identifying extension members

pg_dump: reading schemas

pg_dump: reading user-defined tables
```

after
```
pg_dump: identifying extension members
pg_dump: reading schemas
pg_dump: reading user-defined tables
```

**Comment by tonsV2** [comment]
Thanks for testing!

I tried to change the version to 0.6.1 through the Github UI but it didn't seem to do as I intended. I then tried to commit the change to the dev branch on https://github.com/dhis2-sre/pg-commands but that also isn't showing here :man_shrugging:

**Comment by clementlecorre** [comment]
all right 👍  https://github.com/habx/pg-commands/releases/tag/v0.6.1

**Pull request merged**
